{% set name = "rvc3python" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rvc3python-{{ version }}.tar.gz
  sha256: fe40af09ba7020f35379cfce43d3c2083c1707a030b2e577121534cdec1df74a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - roboticstoolbox-python
    - spatialgeometry
    - spatialmath-python
    - numpy
    - traitlets
    - scipy
    - pygments
    - machinevision-toolbox-python
    - bdsim
    - ipython
    - sympy
    - pytorch
    - torchvision
    - opencv

test:
  imports:
    - RVC3

about:
  home: https://github.com/petercorke/RVC3-python
  summary: 'Support for book: Robotics, Vision & Control 3 in Python'
  dev_url: https://github.com/petercorke/RVC3-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
