{% set name = "rvc3python" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rvc3python-{{ version }}.tar.gz
  sha256: 8c06b5db796a66a85954be8586e760d7b3fd1eb63e1a8db235d938d545d00a97

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - roboticstoolbox-python
    - machinevision-toolbox-python
    - bdsim
    - ipython
    - sympy
    - pytorch
    - torchvision
    - opencv

test:
  imports:
    - RVC3

about:
  home: https://github.com/petercorke/RVC3-python
  summary: 'Support for book: Robotics, Vision & Control 3 in Python'
  dev_url: https://github.com/petercorke/RVC3-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
